treatments:
  - name: blueA_network
    factorIds:
      - 9mWDEEbPMz8J8oWxh
      - dwfYRz6EK4FE9iNcR
      - QEbiEZHHkAaEDEo3q
      - H6mfXThg4jQ2annbb
      - 5G2PioQghwMMQaiDA
      - PhWBYRyqGv7hpZbKm
  - name: blueB_network
    factorIds:
      - 9mWDEEbPMz8J8oWxh
      - dwfYRz6EK4FE9iNcR
      - QEbiEZHHkAaEDEo3q
      - H6mfXThg4jQ2annbb
      - T3s4h67DrihbRNpQS
      - PhWBYRyqGv7hpZbKm
  - name: redA_network
    factorIds:
      - 9mWDEEbPMz8J8oWxh
      - dwfYRz6EK4FE9iNcR
      - LYqRqNsuy3tZGcu7x
      - H6mfXThg4jQ2annbb
      - 5G2PioQghwMMQaiDA
      - PhWBYRyqGv7hpZbKm
  - name: redB_network
    factorIds:
      - 9mWDEEbPMz8J8oWxh
      - dwfYRz6EK4FE9iNcR
      - LYqRqNsuy3tZGcu7x
      - H6mfXThg4jQ2annbb
      - T3s4h67DrihbRNpQS
      - PhWBYRyqGv7hpZbKm
factorTypes:
  - _id: FyNRiLFNYJ5593cHs
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: BBRoq5WHnzs4qpWew
    name: repetitionsWithPartner
    description: how many times do you repeat with a partner
    required: true
    type: String
  - _id: yZ9EAzrPfAEKk96kr
    name: teamColor
    description: are you red or blue?
    required: true
    type: String
  - _id: kJddTH8X4Y6Df7SPA
    name: selectionDuration
    description: >-
      how many seconds do participants have to complete a tangram selection
      trial
    required: true
    type: String
  - _id: 2DXSSGGZYk9nTsqfw
    name: targetSet
    description: which set of tangrams do you see?
    required: true
    type: String
  - _id: oTmtc6KmQb77CaDTC
    name: submitCode
    description: code for submission to prolific/mturk
    required: true
    type: String
factors:
  - _id: LCPL67GcDLnC7kpX4
    name: duo
    value: 2
    factorTypeId: FyNRiLFNYJ5593cHs
  - _id: 9mWDEEbPMz8J8oWxh
    name: quad
    value: 4
    factorTypeId: FyNRiLFNYJ5593cHs
  - _id: dwfYRz6EK4FE9iNcR
    name: four
    value: '4'
    factorTypeId: BBRoq5WHnzs4qpWew
  - _id: LYqRqNsuy3tZGcu7x
    name: red
    value: red
    factorTypeId: yZ9EAzrPfAEKk96kr
  - _id: QEbiEZHHkAaEDEo3q
    name: blue
    value: blue
    factorTypeId: yZ9EAzrPfAEKk96kr
  - _id: H6mfXThg4jQ2annbb
    name: minute
    value: '60'
    factorTypeId: kJddTH8X4Y6Df7SPA
  - _id: sLBbCyDZv74ZsrtYE
    name: solo
    value: 1
    factorTypeId: FyNRiLFNYJ5593cHs
  - _id: GSmgoGszjTjH6mWNu
    name: targetSet
    value: setA
    factorTypeId: kJddTH8X4Y6Df7SPA
    archivedAt: 2021-01-18T21:25:42.882Z
  - _id: 5G2PioQghwMMQaiDA
    name: setA
    value: setA
    factorTypeId: 2DXSSGGZYk9nTsqfw
  - _id: T3s4h67DrihbRNpQS
    name: setB
    value: setB
    factorTypeId: 2DXSSGGZYk9nTsqfw
  - _id: PhWBYRyqGv7hpZbKm
    name: prolificPilot
    value: 3B021164
    factorTypeId: oTmtc6KmQb77CaDTC
lobbyConfigs:
  - name: lobby
    timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
